/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myndk1_MainActivity */

#ifndef _Included_com_example_myndk1_MainActivity
#define _Included_com_example_myndk1_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myndk1_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myndk1_MainActivity_stringFromJNI
  (JNIEnv *env, jobject thiz);

/*
 * Class:     com_example_myndk1_MainActivity
 * Method:    instanceMethodA
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myndk1_MainActivity_instanceMethodA
  (JNIEnv *, jobject);

/*
 * Class:     com_example_myndk1_MainActivity
 * Method:    instance_MethodB
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myndk1_MainActivity_instance_1MethodB
  (JNIEnv *, jobject);

/*
 * Class:     com_example_myndk1_MainActivity
 * Method:    static_method
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myndk1_MainActivity_static_1method
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
